
package com.fal.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FALWebServicesImplService", targetNamespace = "http://impl.ws.fal.com/", wsdlLocation = "http://172.16.8.201:8080/falws/falws?WSDL")
public class FALWebServicesImplService
    extends Service
{

    private final static URL FALWEBSERVICESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FALWEBSERVICESIMPLSERVICE_EXCEPTION;
    private final static QName FALWEBSERVICESIMPLSERVICE_QNAME = new QName("http://impl.ws.fal.com/", "FALWebServicesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.8.201:8080/falws/falws?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FALWEBSERVICESIMPLSERVICE_WSDL_LOCATION = url;
        FALWEBSERVICESIMPLSERVICE_EXCEPTION = e;
    }

    public FALWebServicesImplService() {
        super(__getWsdlLocation(), FALWEBSERVICESIMPLSERVICE_QNAME);
    }

    public FALWebServicesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FALWEBSERVICESIMPLSERVICE_QNAME, features);
    }

    public FALWebServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, FALWEBSERVICESIMPLSERVICE_QNAME);
    }

    public FALWebServicesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FALWEBSERVICESIMPLSERVICE_QNAME, features);
    }

    public FALWebServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FALWebServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FALWebServicesImpl
     */
    @WebEndpoint(name = "FALWebServicesImplPort")
    public FALWebServicesImpl getFALWebServicesImplPort() {
        return super.getPort(new QName("http://impl.ws.fal.com/", "FALWebServicesImplPort"), FALWebServicesImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FALWebServicesImpl
     */
    @WebEndpoint(name = "FALWebServicesImplPort")
    public FALWebServicesImpl getFALWebServicesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.ws.fal.com/", "FALWebServicesImplPort"), FALWebServicesImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FALWEBSERVICESIMPLSERVICE_EXCEPTION!= null) {
            throw FALWEBSERVICESIMPLSERVICE_EXCEPTION;
        }
        return FALWEBSERVICESIMPLSERVICE_WSDL_LOCATION;
    }

}
