
package com.fal.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FALWebServicesImpl", targetNamespace = "http://impl.ws.fal.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FALWebServicesImpl {


    /**
     * 
     * @param lookupRequest
     * @return
     *     returns com.fal.ws.CardLookupResponse
     */
    @WebMethod
    @WebResult(name = "CardLookupResponse", targetNamespace = "")
    @RequestWrapper(localName = "lookupCards", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.LookupCards")
    @ResponseWrapper(localName = "lookupCardsResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.LookupCardsResponse")
    public CardLookupResponse lookupCards(
        @WebParam(name = "LookupRequest", targetNamespace = "")
        CardLookupRequest lookupRequest);

    /**
     * 
     * @param identifier
     * @return
     *     returns com.fal.ws.CardInfoDTO
     */
    @WebMethod
    @WebResult(name = "CardInfoResponse", targetNamespace = "")
    @RequestWrapper(localName = "getCardInfo", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.GetCardInfo")
    @ResponseWrapper(localName = "getCardInfoResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.GetCardInfoResponse")
    public CardInfoDTO getCardInfo(
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier);

    /**
     * 
     * @param svRequest
     * @return
     *     returns com.fal.ws.SvBaseLoyaltyResponse
     */
    @WebMethod(operationName = "SVMessagesRequest")
    @WebResult(name = "SVResponse", targetNamespace = "")
    @RequestWrapper(localName = "SVMessagesRequest", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SVMessagesRequest")
    @ResponseWrapper(localName = "SVMessagesRequestResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SVMessagesRequestResponse")
    public SvBaseLoyaltyResponse svMessagesRequest(
        @WebParam(name = "SVRequest", targetNamespace = "")
        SvBaseLoyaltyRequest svRequest);

    /**
     * 
     * @param brandCode
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "deleteBrand", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteBrand")
    @ResponseWrapper(localName = "deleteBrandResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteBrandResponse")
    public FalBaseResponse deleteBrand(
        @WebParam(name = "BrandCode", targetNamespace = "")
        String brandCode);

    /**
     * 
     * @param currencyCodeFrom
     * @param currencyCodeTo
     * @param currencyRateDate
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "deleteCurrencyRate", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteCurrencyRate")
    @ResponseWrapper(localName = "deleteCurrencyRateResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteCurrencyRateResponse")
    public FalBaseResponse deleteCurrencyRate(
        @WebParam(name = "CurrencyCodeFrom", targetNamespace = "")
        String currencyCodeFrom,
        @WebParam(name = "CurrencyCodeTo", targetNamespace = "")
        String currencyCodeTo,
        @WebParam(name = "CurrencyRateDate", targetNamespace = "")
        XMLGregorianCalendar currencyRateDate);

    /**
     * 
     * @param familyCode
     * @param familyLevel
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "deleteFamilyByLevel", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteFamilyByLevel")
    @ResponseWrapper(localName = "deleteFamilyByLevelResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteFamilyByLevelResponse")
    public FalBaseResponse deleteFamilyByLevel(
        @WebParam(name = "FamilyCode", targetNamespace = "")
        String familyCode,
        @WebParam(name = "FamilyLevel", targetNamespace = "")
        Short familyLevel);

    /**
     * 
     * @param familyCode
     * @param parentFamilyCode
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "deleteFamilyByParent", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteFamilyByParent")
    @ResponseWrapper(localName = "deleteFamilyByParentResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteFamilyByParentResponse")
    public FalBaseResponse deleteFamilyByParent(
        @WebParam(name = "FamilyCode", targetNamespace = "")
        String familyCode,
        @WebParam(name = "ParentFamilyCode", targetNamespace = "")
        String parentFamilyCode);

    /**
     * 
     * @param productCode
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteProductResponse")
    public FalBaseResponse deleteProduct(
        @WebParam(name = "ProductCode", targetNamespace = "")
        String productCode);

    /**
     * 
     * @param tenderCode
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "deleteTender", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteTender")
    @ResponseWrapper(localName = "deleteTenderResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.DeleteTenderResponse")
    public FalBaseResponse deleteTender(
        @WebParam(name = "TenderCode", targetNamespace = "")
        String tenderCode);

    /**
     * 
     * @param identifier
     * @param regionCode
     * @param siteCode
     * @param transactionDate
     * @return
     *     returns com.fal.ws.PersonalRewardsResponse
     */
    @WebMethod
    @WebResult(name = "PersonalRewardsResponse", targetNamespace = "")
    @RequestWrapper(localName = "getPersonalRewards", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.GetPersonalRewards")
    @ResponseWrapper(localName = "getPersonalRewardsResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.GetPersonalRewardsResponse")
    public PersonalRewardsResponse getPersonalRewards(
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier,
        @WebParam(name = "siteCode", targetNamespace = "")
        String siteCode,
        @WebParam(name = "regionCode", targetNamespace = "")
        String regionCode,
        @WebParam(name = "transactionDate", targetNamespace = "")
        XMLGregorianCalendar transactionDate);

    /**
     * 
     * @return
     *     returns com.fal.ws.FalInfoResponse
     */
    @WebMethod
    @WebResult(name = "FalInfoResponse", targetNamespace = "")
    @RequestWrapper(localName = "getVersionInfo", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.GetVersionInfo")
    @ResponseWrapper(localName = "getVersionInfoResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.GetVersionInfoResponse")
    public FalInfoResponse getVersionInfo();

    /**
     * 
     * @param rewardsRequest
     * @return
     *     returns com.fal.ws.RewardsResponse
     */
    @WebMethod
    @WebResult(name = "RewardsResponse", targetNamespace = "")
    @RequestWrapper(localName = "requestRewards", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.RequestRewards")
    @ResponseWrapper(localName = "requestRewardsResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.RequestRewardsResponse")
    public RewardsResponse requestRewards(
        @WebParam(name = "RewardsRequest", targetNamespace = "")
        BasketRequest rewardsRequest);

    /**
     * 
     * @param brand
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "saveBrand", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveBrand")
    @ResponseWrapper(localName = "saveBrandResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveBrandResponse")
    public FalBaseResponse saveBrand(
        @WebParam(name = "Brand", targetNamespace = "")
        BrandDTO brand);

    /**
     * 
     * @param currencyRate
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "saveCurrencyRate", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveCurrencyRate")
    @ResponseWrapper(localName = "saveCurrencyRateResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveCurrencyRateResponse")
    public FalBaseResponse saveCurrencyRate(
        @WebParam(name = "CurrencyRate", targetNamespace = "")
        CurrencyRate currencyRate);

    /**
     * 
     * @param family
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "saveFamily", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveFamily")
    @ResponseWrapper(localName = "saveFamilyResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveFamilyResponse")
    public FalBaseResponse saveFamily(
        @WebParam(name = "Family", targetNamespace = "")
        FamilyDTO family);

    /**
     * 
     * @param product
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "saveProduct", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveProduct")
    @ResponseWrapper(localName = "saveProductResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveProductResponse")
    public FalBaseResponse saveProduct(
        @WebParam(name = "Product", targetNamespace = "")
        ProductDTO product);

    /**
     * 
     * @param productPrice
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "saveProductPrice", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveProductPrice")
    @ResponseWrapper(localName = "saveProductPriceResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveProductPriceResponse")
    public FalBaseResponse saveProductPrice(
        @WebParam(name = "ProductPrice", targetNamespace = "")
        ProductPriceDTO productPrice);

    /**
     * 
     * @param tender
     * @return
     *     returns com.fal.ws.FalBaseResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "saveTender", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveTender")
    @ResponseWrapper(localName = "saveTenderResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SaveTenderResponse")
    public FalBaseResponse saveTender(
        @WebParam(name = "Tender", targetNamespace = "")
        Tender tender);

    /**
     * 
     * @param identifier
     * @param beaconCode
     * @param siteCode
     * @param numberOfProducts
     * @param transactionDate
     * @return
     *     returns com.fal.ws.ProductPromotionResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suggestProductPromotions", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SuggestProductPromotions")
    @ResponseWrapper(localName = "suggestProductPromotionsResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.SuggestProductPromotionsResponse")
    public ProductPromotionResponse suggestProductPromotions(
        @WebParam(name = "identifier", targetNamespace = "")
        String identifier,
        @WebParam(name = "siteCode", targetNamespace = "")
        String siteCode,
        @WebParam(name = "beaconCode", targetNamespace = "")
        String beaconCode,
        @WebParam(name = "transactionDate", targetNamespace = "")
        XMLGregorianCalendar transactionDate,
        @WebParam(name = "numberOfProducts", targetNamespace = "")
        int numberOfProducts);

    /**
     * 
     * @param basket
     * @return
     *     returns com.fal.ws.BaseLoyaltyResponse
     */
    @WebMethod
    @WebResult(name = "ResponseMessage", targetNamespace = "")
    @RequestWrapper(localName = "validateCoupon", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.ValidateCoupon")
    @ResponseWrapper(localName = "validateCouponResponse", targetNamespace = "http://impl.ws.fal.com/", className = "com.fal.ws.ValidateCouponResponse")
    public BaseLoyaltyResponse validateCoupon(
        @WebParam(name = "Basket", targetNamespace = "")
        BasketRequest basket);

}
