
package co.com.flamingo.clienteRetanqueo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "swRetanqueo", targetNamespace = "http://www.flamingo.com.co", wsdlLocation = "http://172.16.8.24/SWRETANQUEO/swRetanqueo.svc?wsdl")
public class SwRetanqueo
    extends Service
{

    private final static URL SWRETANQUEO_WSDL_LOCATION;
    private final static WebServiceException SWRETANQUEO_EXCEPTION;
    private final static QName SWRETANQUEO_QNAME = new QName("http://www.flamingo.com.co", "swRetanqueo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.8.24/SWRETANQUEO/swRetanqueo.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SWRETANQUEO_WSDL_LOCATION = url;
        SWRETANQUEO_EXCEPTION = e;
    }

    public SwRetanqueo() {
        super(__getWsdlLocation(), SWRETANQUEO_QNAME);
    }

    public SwRetanqueo(WebServiceFeature... features) {
        super(__getWsdlLocation(), SWRETANQUEO_QNAME, features);
    }

    public SwRetanqueo(URL wsdlLocation) {
        super(wsdlLocation, SWRETANQUEO_QNAME);
    }

    public SwRetanqueo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SWRETANQUEO_QNAME, features);
    }

    public SwRetanqueo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SwRetanqueo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRetanqueo
     */
    @WebEndpoint(name = "iRetanqueo")
    public IRetanqueo getIRetanqueo() {
        return super.getPort(new QName("http://www.flamingo.com.co", "iRetanqueo"), IRetanqueo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRetanqueo
     */
    @WebEndpoint(name = "iRetanqueo")
    public IRetanqueo getIRetanqueo(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.flamingo.com.co", "iRetanqueo"), IRetanqueo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SWRETANQUEO_EXCEPTION!= null) {
            throw SWRETANQUEO_EXCEPTION;
        }
        return SWRETANQUEO_WSDL_LOCATION;
    }

}
