
package co.com.flamingo.clienteRetanqueo;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "iRetanqueo", targetNamespace = "http://www.flamingo.com.co")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRetanqueo {


    /**
     * 
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.RespuestaMetodo
     */
    @WebMethod(operationName = "TraerDatosServidor", action = "http://www.flamingo.com.co/iRetanqueo/TraerDatosServidor")
    @WebResult(name = "TraerDatosServidorResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "TraerDatosServidor", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.TraerDatosServidor")
    @ResponseWrapper(localName = "TraerDatosServidorResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.TraerDatosServidorResponse")
    public RespuestaMetodo traerDatosServidor();

    /**
     * 
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.RetanqueoRes
     */
    @WebMethod(operationName = "ConsultarRetanqueo", action = "http://www.flamingo.com.co/iRetanqueo/ConsultarRetanqueo")
    @WebResult(name = "ConsultarRetanqueoResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsultarRetanqueo", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarRetanqueo")
    @ResponseWrapper(localName = "ConsultarRetanqueoResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarRetanqueoResponse")
    public RetanqueoRes consultarRetanqueo(
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        ClienteCer pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.RetanqueoActualizarRes
     */
    @WebMethod(operationName = "ActualizarRetanqueo", action = "http://www.flamingo.com.co/iRetanqueo/ActualizarRetanqueo")
    @WebResult(name = "ActualizarRetanqueoResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ActualizarRetanqueo", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ActualizarRetanqueo")
    @ResponseWrapper(localName = "ActualizarRetanqueoResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ActualizarRetanqueoResponse")
    public RetanqueoActualizarRes actualizarRetanqueo(
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        ClienteActualizar pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsultarSaldoNugRes
     */
    @WebMethod(operationName = "ConsultarSaldoNug", action = "http://www.flamingo.com.co/iRetanqueo/ConsultarSaldoNug")
    @WebResult(name = "ConsultarSaldoNugResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsultarSaldoNug", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarSaldoNug")
    @ResponseWrapper(localName = "ConsultarSaldoNugResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarSaldoNugResponse")
    public ConsultarSaldoNugRes consultarSaldoNug(
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        ClienteCer pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsultarSaldoNugRes
     */
    @WebMethod(operationName = "ActualizarNug", action = "http://www.flamingo.com.co/iRetanqueo/ActualizarNug")
    @WebResult(name = "ActualizarNugResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ActualizarNug", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ActualizarNug")
    @ResponseWrapper(localName = "ActualizarNugResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ActualizarNugResponse")
    public ConsultarSaldoNugRes actualizarNug(
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        ClienteActualizar pCliente);

    /**
     * 
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsultarClienteRes
     */
    @WebMethod(operationName = "ConsultarCliente", action = "http://www.flamingo.com.co/iRetanqueo/ConsultarCliente")
    @WebResult(name = "ConsultarClienteResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsultarCliente", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarCliente")
    @ResponseWrapper(localName = "ConsultarClienteResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarClienteResponse")
    public ConsultarClienteRes consultarCliente(
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        ClienteConsultar pCliente);

    /**
     * 
     * @param pSimulacion
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.SimularCuotaRes
     */
    @WebMethod(operationName = "SimularCuota", action = "http://www.flamingo.com.co/iRetanqueo/SimularCuota")
    @WebResult(name = "SimularCuotaResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "SimularCuota", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularCuota")
    @ResponseWrapper(localName = "SimularCuotaResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularCuotaResponse")
    public SimularCuotaRes simularCuota(
        @WebParam(name = "pSimulacion", targetNamespace = "http://www.flamingo.com.co")
        SimulacionCuota pSimulacion);

    /**
     * 
     * @param password
     * @param pAliado
     * @param user
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.TokenRes
     */
    @WebMethod(operationName = "GenerarToken", action = "http://www.flamingo.com.co/iRetanqueo/GenerarToken")
    @WebResult(name = "GenerarTokenResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "GenerarToken", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.GenerarToken")
    @ResponseWrapper(localName = "GenerarTokenResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.GenerarTokenResponse")
    public TokenRes generarToken(
        @WebParam(name = "pAliado", targetNamespace = "http://www.flamingo.com.co")
        Aliado pAliado,
        @WebParam(name = "user", targetNamespace = "http://www.flamingo.com.co")
        String user,
        @WebParam(name = "password", targetNamespace = "http://www.flamingo.com.co")
        String password);

    /**
     * 
     * @param pIngreso
     * @param pAprobacion
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.CrearAprobacionRes
     */
    @WebMethod(operationName = "CrearAprobacion", action = "http://www.flamingo.com.co/iRetanqueo/CrearAprobacion")
    @WebResult(name = "CrearAprobacionResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "CrearAprobacion", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.CrearAprobacion")
    @ResponseWrapper(localName = "CrearAprobacionResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.CrearAprobacionResponse")
    public CrearAprobacionRes crearAprobacion(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pAprobacion", targetNamespace = "http://www.flamingo.com.co")
        Aprobacion pAprobacion);

    /**
     * 
     * @param pValorAprobacion
     * @param pDireccionEmail
     * @param pNug
     * @param pCelular
     * @param pFechaInicio
     * @param pCodigoSeguro
     * @param pTerminal
     * @param pCedulaVendedor
     * @param pIdCliente
     * @param pSucursal
     * @param pCodigoZona
     * @param pSeguro
     * @param pAfianzadora
     * @param pSolicitud
     * @param pEmail
     * @param pEstadoAprobacion
     * @param pNumeroCelular
     * @param pFormaPago
     * @param pTipoIdCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.AprobacionDigitalRes
     */
    @WebMethod(operationName = "AprobacionDigital", action = "http://www.flamingo.com.co/iRetanqueo/AprobacionDigital")
    @WebResult(name = "AprobacionDigitalResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "AprobacionDigital", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.AprobacionDigital")
    @ResponseWrapper(localName = "AprobacionDigitalResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.AprobacionDigitalResponse")
    public AprobacionDigitalRes aprobacionDigital(
        @WebParam(name = "pIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pIdCliente,
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente,
        @WebParam(name = "pSucursal", targetNamespace = "http://www.flamingo.com.co")
        String pSucursal,
        @WebParam(name = "pCodigoZona", targetNamespace = "http://www.flamingo.com.co")
        String pCodigoZona,
        @WebParam(name = "pValorAprobacion", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pValorAprobacion,
        @WebParam(name = "pFechaInicio", targetNamespace = "http://www.flamingo.com.co")
        XMLGregorianCalendar pFechaInicio,
        @WebParam(name = "pFormaPago", targetNamespace = "http://www.flamingo.com.co")
        String pFormaPago,
        @WebParam(name = "pTerminal", targetNamespace = "http://www.flamingo.com.co")
        String pTerminal,
        @WebParam(name = "pNug", targetNamespace = "http://www.flamingo.com.co")
        String pNug,
        @WebParam(name = "pSolicitud", targetNamespace = "http://www.flamingo.com.co")
        String pSolicitud,
        @WebParam(name = "pSeguro", targetNamespace = "http://www.flamingo.com.co")
        String pSeguro,
        @WebParam(name = "pCodigoSeguro", targetNamespace = "http://www.flamingo.com.co")
        String pCodigoSeguro,
        @WebParam(name = "pCelular", targetNamespace = "http://www.flamingo.com.co")
        String pCelular,
        @WebParam(name = "pNumeroCelular", targetNamespace = "http://www.flamingo.com.co")
        String pNumeroCelular,
        @WebParam(name = "pEmail", targetNamespace = "http://www.flamingo.com.co")
        String pEmail,
        @WebParam(name = "pDireccionEmail", targetNamespace = "http://www.flamingo.com.co")
        String pDireccionEmail,
        @WebParam(name = "pEstadoAprobacion", targetNamespace = "http://www.flamingo.com.co")
        String pEstadoAprobacion,
        @WebParam(name = "pAfianzadora", targetNamespace = "http://www.flamingo.com.co")
        String pAfianzadora,
        @WebParam(name = "pCedulaVendedor", targetNamespace = "http://www.flamingo.com.co")
        String pCedulaVendedor);

    /**
     * 
     * @param pIngreso
     * @param pNumeroAprobacion
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsultarPlanPagosRes
     */
    @WebMethod(operationName = "ConsultarPlanPagos", action = "http://www.flamingo.com.co/iRetanqueo/ConsultarPlanPagos")
    @WebResult(name = "ConsultarPlanPagosResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsultarPlanPagos", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarPlanPagos")
    @ResponseWrapper(localName = "ConsultarPlanPagosResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarPlanPagosResponse")
    public ConsultarPlanPagosRes consultarPlanPagos(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pNumeroAprobacion", targetNamespace = "http://www.flamingo.com.co")
        String pNumeroAprobacion);

    /**
     * 
     * @param pIngreso
     * @param pNumeroAprobacion
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.DesbloquearAprobacionRes
     */
    @WebMethod(operationName = "DesbloquearAprobacion", action = "http://www.flamingo.com.co/iRetanqueo/DesbloquearAprobacion")
    @WebResult(name = "DesbloquearAprobacionResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "DesbloquearAprobacion", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.DesbloquearAprobacion")
    @ResponseWrapper(localName = "DesbloquearAprobacionResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.DesbloquearAprobacionResponse")
    public DesbloquearAprobacionRes desbloquearAprobacion(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pNumeroAprobacion", targetNamespace = "http://www.flamingo.com.co")
        String pNumeroAprobacion);

    /**
     * 
     * @param pIdCliente
     * @param pEstado
     * @param pNumeroAprobacion
     * @param pTipoIdCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.DesbloquearDigitalRes
     */
    @WebMethod(operationName = "DesbloquearDigital", action = "http://www.flamingo.com.co/iRetanqueo/DesbloquearDigital")
    @WebResult(name = "DesbloquearDigitalResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "DesbloquearDigital", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.DesbloquearDigital")
    @ResponseWrapper(localName = "DesbloquearDigitalResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.DesbloquearDigitalResponse")
    public DesbloquearDigitalRes desbloquearDigital(
        @WebParam(name = "pIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pIdCliente,
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente,
        @WebParam(name = "pNumeroAprobacion", targetNamespace = "http://www.flamingo.com.co")
        String pNumeroAprobacion,
        @WebParam(name = "pEstado", targetNamespace = "http://www.flamingo.com.co")
        String pEstado);

    /**
     * 
     * @param pIdCliente
     * @param pEstado
     * @param pTipoIdCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.DesbloquearDocumentoDigitalRes
     */
    @WebMethod(operationName = "DesbloquearDocumentoDigital", action = "http://www.flamingo.com.co/iRetanqueo/DesbloquearDocumentoDigital")
    @WebResult(name = "DesbloquearDocumentoDigitalResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "DesbloquearDocumentoDigital", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.DesbloquearDocumentoDigital")
    @ResponseWrapper(localName = "DesbloquearDocumentoDigitalResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.DesbloquearDocumentoDigitalResponse")
    public DesbloquearDocumentoDigitalRes desbloquearDocumentoDigital(
        @WebParam(name = "pIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pIdCliente,
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente,
        @WebParam(name = "pEstado", targetNamespace = "http://www.flamingo.com.co")
        String pEstado);

    /**
     * 
     * @param pIngreso
     * @param pValorAprobacion
     * @param pNumeroAprobacion
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.SimularPlanPagosRes
     */
    @WebMethod(operationName = "SimularPlanPagos", action = "http://www.flamingo.com.co/iRetanqueo/SimularPlanPagos")
    @WebResult(name = "SimularPlanPagosResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "SimularPlanPagos", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularPlanPagos")
    @ResponseWrapper(localName = "SimularPlanPagosResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularPlanPagosResponse")
    public SimularPlanPagosRes simularPlanPagos(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pNumeroAprobacion", targetNamespace = "http://www.flamingo.com.co")
        String pNumeroAprobacion,
        @WebParam(name = "pValorAprobacion", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pValorAprobacion,
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        String pCliente);

    /**
     * 
     * @param pIngreso
     * @param pIdCliente
     * @param pValorTarjeta
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.CrearTarjetaEcommerceRes
     */
    @WebMethod(operationName = "CrearTarjetaEcommerce", action = "http://www.flamingo.com.co/iRetanqueo/CrearTarjetaEcommerce")
    @WebResult(name = "CrearTarjetaEcommerceResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "CrearTarjetaEcommerce", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.CrearTarjetaEcommerce")
    @ResponseWrapper(localName = "CrearTarjetaEcommerceResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.CrearTarjetaEcommerceResponse")
    public CrearTarjetaEcommerceRes crearTarjetaEcommerce(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pIdCliente,
        @WebParam(name = "pValorTarjeta", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pValorTarjeta);

    /**
     * 
     * @param pIngreso
     * @param pFecha
     * @param pIdAlmacenPOS
     * @param pIDCliente
     * @param pValorConsumo
     * @param pIdTransaccion
     * @param pNumTarjeta
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsumoTarjetaRes
     */
    @WebMethod(operationName = "ConsumoTarjetaEcommerce", action = "http://www.flamingo.com.co/iRetanqueo/ConsumoTarjetaEcommerce")
    @WebResult(name = "ConsumoTarjetaEcommerceResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsumoTarjetaEcommerce", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsumoTarjetaEcommerce")
    @ResponseWrapper(localName = "ConsumoTarjetaEcommerceResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsumoTarjetaEcommerceResponse")
    public ConsumoTarjetaRes consumoTarjetaEcommerce(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pFecha", targetNamespace = "http://www.flamingo.com.co")
        XMLGregorianCalendar pFecha,
        @WebParam(name = "p_IdTransaccion", targetNamespace = "http://www.flamingo.com.co")
        String pIdTransaccion,
        @WebParam(name = "pIdAlmacenPOS", targetNamespace = "http://www.flamingo.com.co")
        String pIdAlmacenPOS,
        @WebParam(name = "pNumTarjeta", targetNamespace = "http://www.flamingo.com.co")
        String pNumTarjeta,
        @WebParam(name = "pIDCliente", targetNamespace = "http://www.flamingo.com.co")
        String pIDCliente,
        @WebParam(name = "pValorConsumo", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pValorConsumo);

    /**
     * 
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsultarSegurosRes
     */
    @WebMethod(operationName = "ConsultarSeguros", action = "http://www.flamingo.com.co/iRetanqueo/ConsultarSeguros")
    @WebResult(name = "ConsultarSegurosResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsultarSeguros", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarSeguros")
    @ResponseWrapper(localName = "ConsultarSegurosResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarSegurosResponse")
    public ConsultarSegurosRes consultarSeguros();

    /**
     * 
     * @param pIdCliente
     * @param pNumAprobacion
     * @param pTipoIdCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.ConsultarAprobacionRes
     */
    @WebMethod(operationName = "ConsultarAprobacion", action = "http://www.flamingo.com.co/iRetanqueo/ConsultarAprobacion")
    @WebResult(name = "ConsultarAprobacionResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "ConsultarAprobacion", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarAprobacion")
    @ResponseWrapper(localName = "ConsultarAprobacionResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.ConsultarAprobacionResponse")
    public ConsultarAprobacionRes consultarAprobacion(
        @WebParam(name = "pIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pIdCliente,
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente,
        @WebParam(name = "pNumAprobacion", targetNamespace = "http://www.flamingo.com.co")
        Integer pNumAprobacion);

    /**
     * 
     * @param pFechaAlta
     * @param pVendedor
     * @param pCliente
     * @param pCodigoZona
     * @param pSucursal
     * @param pSolicitud
     * @param pPlazo
     * @param pAliado
     * @param pCodigoCanal
     * @param pOrigen
     * @param pValor
     * @param pFechaRegistro
     * @param pTipoIdCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.GrabarSolicitudRes
     */
    @WebMethod(operationName = "GrabarSolicitud", action = "http://www.flamingo.com.co/iRetanqueo/GrabarSolicitud")
    @WebResult(name = "GrabarSolicitudResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "GrabarSolicitud", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.GrabarSolicitud")
    @ResponseWrapper(localName = "GrabarSolicitudResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.GrabarSolicitudResponse")
    public GrabarSolicitudRes grabarSolicitud(
        @WebParam(name = "pSolicitud", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pSolicitud,
        @WebParam(name = "pCodigoZona", targetNamespace = "http://www.flamingo.com.co")
        String pCodigoZona,
        @WebParam(name = "pValor", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pValor,
        @WebParam(name = "pPlazo", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pPlazo,
        @WebParam(name = "pFechaRegistro", targetNamespace = "http://www.flamingo.com.co")
        XMLGregorianCalendar pFechaRegistro,
        @WebParam(name = "pFechaAlta", targetNamespace = "http://www.flamingo.com.co")
        XMLGregorianCalendar pFechaAlta,
        @WebParam(name = "pVendedor", targetNamespace = "http://www.flamingo.com.co")
        String pVendedor,
        @WebParam(name = "pCodigoCanal", targetNamespace = "http://www.flamingo.com.co")
        String pCodigoCanal,
        @WebParam(name = "pAliado", targetNamespace = "http://www.flamingo.com.co")
        String pAliado,
        @WebParam(name = "pSucursal", targetNamespace = "http://www.flamingo.com.co")
        String pSucursal,
        @WebParam(name = "pOrigen", targetNamespace = "http://www.flamingo.com.co")
        String pOrigen,
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        String pCliente,
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente);

    /**
     * 
     * @param pCodigoZona
     * @param pAfianzadora
     * @param pFecha
     * @param pTipoIdCliente
     * @param pCliente
     * @param pUsuario
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.CustodiaDocumentosRes
     */
    @WebMethod(operationName = "CustodiaDocumentos", action = "http://www.flamingo.com.co/iRetanqueo/CustodiaDocumentos")
    @WebResult(name = "CustodiaDocumentosResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "CustodiaDocumentos", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.CustodiaDocumentos")
    @ResponseWrapper(localName = "CustodiaDocumentosResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.CustodiaDocumentosResponse")
    public CustodiaDocumentosRes custodiaDocumentos(
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente,
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        String pCliente,
        @WebParam(name = "pCodigoZona", targetNamespace = "http://www.flamingo.com.co")
        String pCodigoZona,
        @WebParam(name = "pFecha", targetNamespace = "http://www.flamingo.com.co")
        XMLGregorianCalendar pFecha,
        @WebParam(name = "pUsuario", targetNamespace = "http://www.flamingo.com.co")
        String pUsuario,
        @WebParam(name = "pAfianzadora", targetNamespace = "http://www.flamingo.com.co")
        String pAfianzadora);

    /**
     * 
     * @param pSimulacionCuota
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.SimularCuotaModalidadRes
     */
    @WebMethod(operationName = "SimularCuotaModalidad", action = "http://www.flamingo.com.co/iRetanqueo/SimularCuotaModalidad")
    @WebResult(name = "SimularCuotaModalidadResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "SimularCuotaModalidad", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularCuotaModalidad")
    @ResponseWrapper(localName = "SimularCuotaModalidadResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularCuotaModalidadResponse")
    public SimularCuotaModalidadRes simularCuotaModalidad(
        @WebParam(name = "pSimulacionCuota", targetNamespace = "http://www.flamingo.com.co")
        SimulacionCuotaModalidad pSimulacionCuota);

    /**
     * 
     * @param pIngreso
     * @param pValorAprobacion
     * @param pCodigoZona
     * @param pNumeroCuotas
     * @param pFormaPago
     * @param pNumeroAprobacion
     * @param pTipoIdCliente
     * @param pCliente
     * @return
     *     returns co.com.flamingo.clienteRetanqueo.SimularPlanPagosDigitalesRes
     */
    @WebMethod(operationName = "SimularPlanPagosDigitales", action = "http://www.flamingo.com.co/iRetanqueo/SimularPlanPagosDigitales")
    @WebResult(name = "SimularPlanPagosDigitalesResult", targetNamespace = "http://www.flamingo.com.co")
    @RequestWrapper(localName = "SimularPlanPagosDigitales", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularPlanPagosDigitales")
    @ResponseWrapper(localName = "SimularPlanPagosDigitalesResponse", targetNamespace = "http://www.flamingo.com.co", className = "co.com.flamingo.clienteRetanqueo.SimularPlanPagosDigitalesResponse")
    public SimularPlanPagosDigitalesRes simularPlanPagosDigitales(
        @WebParam(name = "pIngreso", targetNamespace = "http://www.flamingo.com.co")
        Autenticacion pIngreso,
        @WebParam(name = "pNumeroAprobacion", targetNamespace = "http://www.flamingo.com.co")
        String pNumeroAprobacion,
        @WebParam(name = "pValorAprobacion", targetNamespace = "http://www.flamingo.com.co")
        BigDecimal pValorAprobacion,
        @WebParam(name = "pNumeroCuotas", targetNamespace = "http://www.flamingo.com.co")
        Integer pNumeroCuotas,
        @WebParam(name = "pCodigoZona", targetNamespace = "http://www.flamingo.com.co")
        String pCodigoZona,
        @WebParam(name = "pTipoIdCliente", targetNamespace = "http://www.flamingo.com.co")
        String pTipoIdCliente,
        @WebParam(name = "pCliente", targetNamespace = "http://www.flamingo.com.co")
        String pCliente,
        @WebParam(name = "pFormaPago", targetNamespace = "http://www.flamingo.com.co")
        String pFormaPago);

}
